_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "faster_rcnn_R_50_FPN_3x_model_final_280758.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50

DATASETS:
  # TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  TRAIN: ("nightowls_train",)
  # TEST: ("nightowls_val",)

INPUT:
  # MIN_SIZE_TRAIN: (320, 512)
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TRAIN: (640, 800)

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 24
  BASE_LR: 0.02
  STEPS: (40000, 53000)
  MAX_ITER: 60000

TEST:
  EVAL_PERIOD: 1000

# OUTPUT_DIR: "./output/test_R_50_FPN_1x"
