_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "cascade_rcnn_swin_l"
  MASK_ON: False
  WEIGHTS: "detectron2://ViTDet/COCO/cascade_mask_rcnn_swin_l_in21k/f342979186/model_final_7c897e.pkl"
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  ROI_HEADS:
    NUM_CLASSES: 80
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]

DATALOADER:
  NUM_WORKERS: 1

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

INPUT:
  FORMAT: "RGB"

SOLVER:
  AMP:
    ENABLED: True

  IMS_PER_BATCH: 16
  MAX_ITER: 7500
  STEPS: (3000, 6500)
  WARMUP_ITERS: 100
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 1500

TEST:
  EVAL_PERIOD: 300

OUTPUT_DIR: "/Data/Models"
