_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "mask_rcnn_R_101_FPN_3x_model_final_a3ec72.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
# SOLVER:
#   STEPS: (210000, 250000)
#   MAX_ITER: 270000

DATASETS:
  TRAIN: ("coco_2017_train", "nightowls_train")
  TEST: ("coco_2017_val","nightowls_val")
  #TRAIN: ("nightowls_train",)
  #TEST: ("nightowls_val",)

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (30000, 60000, 90000)
  MAX_ITER: 120000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "./output/Train_Mask_R_101_FPN"
