_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "Cascade-MViTv2-Base"
  MASK_ON: False
  # WEIGHTS: "detectron2://ViTDet/COCO/cascade_mask_rcnn_mvitv2_b_in21k/f325820315/model_final_8c3da3.pkl"
  WEIGHTS: "Cascade_RCNN_MViTv2-B_640_COCO.pth"

DATALOADER:
  NUM_WORKERS: 1

DATASETS:
  TRAIN: ("coco_2017_train_100_plus_shots","nightowls_train_231_shots")
  TEST: ("coco_2017_val","nightowls_val","nightowls_train_231_shots")

INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 640

SOLVER:
  AMP:
    ENABLED: True
  # COCO:                    1 epoch == 117266
  # COCO + NightOwls:        1 epoch == 147330
  # COCO100 + NightOwls:     1 epoch == 33147
  # COCO50 + NightOwls:      1 epoch == 31663
  # COCO10 + NightOwls:      1 epoch == 30450
  #
  # COCO100 + NightOwls14:   1 epoch == 3089
  # COCO100 + NightOwls28:   1 epoch == 3096
  # COCO100 + NightOwls53:   1 epoch == 3106
  # COCO100 + NightOwls231:  1 epoch == 3193
  STEPS: (5000, 11500)
  MAX_ITER: 12000

TEST:
  EVAL_PERIOD: 1500

OUTPUT_DIR: "output/Cascade_RCNN_MViTv2-B_640_COCO100_NO231_L1_120e"
