_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "Cascade-MViTv2-Base"
  MASK_ON: False
  WEIGHTS: "Cascade_RCNN_MViTv2-Base_640.pth"

DATALOADER:
  NUM_WORKERS: 1

DATASETS:
  TRAIN: ("coco_2017_train", "nightowls_train")
  TEST: ("coco_2017_val","nightowls_val")

INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512

SOLVER:
  AMP:
    ENABLED: True
  # 20*7500 = 150000 ~ 1 epoch
  STEPS: (15000, 60000)
  MAX_ITER: 75000 # 7500*10 (~10 epochs)

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: "output/Cascade_RCNN_MViTv2-Base_512"
