_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "Cascade-MViTv2-Base"
  MASK_ON: False
  WEIGHTS: "detectron2://ViTDet/COCO/cascade_mask_rcnn_mvitv2_b_in21k/f325820315/model_final_8c3da3.pkl"

DATALOADER:
  NUM_WORKERS: 1

DATASETS:
  TRAIN: ("coco_2017_train", )  # NOTE: For training dataset, using config in nightowls.py.
  TEST: ("coco_2017_val",)
  # TEST: ("coco_2017_val","nightowls_val")

INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 320

SOLVER:
  AMP:
    ENABLED: True
  # COCO:              1 epoch == 117266
  # COCO + NightOwls:  1 epoch ==
  STEPS: (8000, 52000)
  MAX_ITER: 60000  # COCO ~15 epochs with batch size 30 (2 GPU's, i.e., 15 per GPU)

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: "output/Cascade_RCNN_MViTv2-B_320"
